apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ../ingress-nginx
  - argocd-ingress.yaml


# This patch adds the IAM Role you created in Step A to the ArgoCD ServiceAccount
patches:
  - target:
      kind: ServiceAccount
      name: argocd-server
    patch: |-
      - op: add
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::149850910638:role/argocd-server-role