# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "my-eks-state-123456789012"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "dev/services/argocd/terraform.tfstate"
    region         = "us-east-1"
  }
}
